leftnav:
- identifier: 107c5886-444d-f05e-b2a3-0e1d2833de64
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 9cb78541-d750-5e6a-c55f-a9a7e9f78a4d
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 5efee89c-b82a-16dd-a1b9-492fa64708d3
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 17f80790-6573-2a22-b323-8a6c6e3417ed
  name: Projects
  url: /pages/projects
  weight: 40
- identifier: 31a752e8-9d6e-6012-5a57-9bf55a73d81d
  name: Related Resources
  url: /pages/related-resources
  weight: 50
